# Generated by Django 4.2.3 on 2023-10-21 20:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_thumbnail_product_image_remove_product_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image3'),
        ),
    ]
