# Generated by Django 4.2.3 on 2023-10-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_image2_alter_product_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='second_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='third_image',
        ),
    ]
