# Generated by Django 4.2.3 on 2023-10-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_image2_product_second_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
    ]
